[package]
name = "turs"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.24"
tokio = { version = "1.21.1", features = ["full"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
